// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.9.2
// source: qrcode.proto

package rpc_goo

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type QRCodeGetParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url  string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Size int32  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *QRCodeGetParams) Reset() {
	*x = QRCodeGetParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qrcode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QRCodeGetParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRCodeGetParams) ProtoMessage() {}

func (x *QRCodeGetParams) ProtoReflect() protoreflect.Message {
	mi := &file_qrcode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRCodeGetParams.ProtoReflect.Descriptor instead.
func (*QRCodeGetParams) Descriptor() ([]byte, []int) {
	return file_qrcode_proto_rawDescGZIP(), []int{0}
}

func (x *QRCodeGetParams) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *QRCodeGetParams) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type QRCodeGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode     int32  `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg      string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	Base64Image string `protobuf:"bytes,3,opt,name=base64image,proto3" json:"base64image,omitempty"`
}

func (x *QRCodeGetResponse) Reset() {
	*x = QRCodeGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qrcode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QRCodeGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRCodeGetResponse) ProtoMessage() {}

func (x *QRCodeGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qrcode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRCodeGetResponse.ProtoReflect.Descriptor instead.
func (*QRCodeGetResponse) Descriptor() ([]byte, []int) {
	return file_qrcode_proto_rawDescGZIP(), []int{1}
}

func (x *QRCodeGetResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *QRCodeGetResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *QRCodeGetResponse) GetBase64Image() string {
	if x != nil {
		return x.Base64Image
	}
	return ""
}

var File_qrcode_proto protoreflect.FileDescriptor

var file_qrcode_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x71, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x72, 0x70, 0x63, 0x5f, 0x67, 0x6f, 0x6f, 0x1a, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a,
	0x0f, 0x51, 0x52, 0x43, 0x6f, 0x64, 0x65, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x69, 0x0a, 0x11, 0x51, 0x52, 0x43, 0x6f, 0x64, 0x65,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65,
	0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65,
	0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x12,
	0x20, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x36, 0x34, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x36, 0x34, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x32, 0x4e, 0x0a, 0x0d, 0x51, 0x52, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3d, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x18, 0x2e, 0x72, 0x70, 0x63, 0x5f,
	0x67, 0x6f, 0x6f, 0x2e, 0x51, 0x52, 0x43, 0x6f, 0x64, 0x65, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x1a, 0x1a, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x6f, 0x6f, 0x2e, 0x51, 0x52,
	0x43, 0x6f, 0x64, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_qrcode_proto_rawDescOnce sync.Once
	file_qrcode_proto_rawDescData = file_qrcode_proto_rawDesc
)

func file_qrcode_proto_rawDescGZIP() []byte {
	file_qrcode_proto_rawDescOnce.Do(func() {
		file_qrcode_proto_rawDescData = protoimpl.X.CompressGZIP(file_qrcode_proto_rawDescData)
	})
	return file_qrcode_proto_rawDescData
}

var file_qrcode_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_qrcode_proto_goTypes = []interface{}{
	(*QRCodeGetParams)(nil),   // 0: rpc_goo.QRCodeGetParams
	(*QRCodeGetResponse)(nil), // 1: rpc_goo.QRCodeGetResponse
}
var file_qrcode_proto_depIdxs = []int32{
	0, // 0: rpc_goo.QRCodeService.Get:input_type -> rpc_goo.QRCodeGetParams
	1, // 1: rpc_goo.QRCodeService.Get:output_type -> rpc_goo.QRCodeGetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_qrcode_proto_init() }
func file_qrcode_proto_init() {
	if File_qrcode_proto != nil {
		return
	}
	file_common_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_qrcode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QRCodeGetParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qrcode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QRCodeGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qrcode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qrcode_proto_goTypes,
		DependencyIndexes: file_qrcode_proto_depIdxs,
		MessageInfos:      file_qrcode_proto_msgTypes,
	}.Build()
	File_qrcode_proto = out.File
	file_qrcode_proto_rawDesc = nil
	file_qrcode_proto_goTypes = nil
	file_qrcode_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// QRCodeServiceClient is the client API for QRCodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QRCodeServiceClient interface {
	Get(ctx context.Context, in *QRCodeGetParams, opts ...grpc.CallOption) (*QRCodeGetResponse, error)
}

type qRCodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQRCodeServiceClient(cc grpc.ClientConnInterface) QRCodeServiceClient {
	return &qRCodeServiceClient{cc}
}

func (c *qRCodeServiceClient) Get(ctx context.Context, in *QRCodeGetParams, opts ...grpc.CallOption) (*QRCodeGetResponse, error) {
	out := new(QRCodeGetResponse)
	err := c.cc.Invoke(ctx, "/rpc_goo.QRCodeService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QRCodeServiceServer is the server API for QRCodeService service.
type QRCodeServiceServer interface {
	Get(context.Context, *QRCodeGetParams) (*QRCodeGetResponse, error)
}

// UnimplementedQRCodeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedQRCodeServiceServer struct {
}

func (*UnimplementedQRCodeServiceServer) Get(context.Context, *QRCodeGetParams) (*QRCodeGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterQRCodeServiceServer(s *grpc.Server, srv QRCodeServiceServer) {
	s.RegisterService(&_QRCodeService_serviceDesc, srv)
}

func _QRCodeService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QRCodeGetParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QRCodeServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_goo.QRCodeService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QRCodeServiceServer).Get(ctx, req.(*QRCodeGetParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _QRCodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc_goo.QRCodeService",
	HandlerType: (*QRCodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _QRCodeService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qrcode.proto",
}
